-- bundle_recon icin ScanPackage satiri (Order.packageId FK). deploy seed calistirmadigi
-- icin burada olusturulur (idempotent). Rapor KOD tarafindan (generateBundleReconReport)
-- uretilir; promptTemplate placeholder. Bu satirin varligi routes/orders.ts'te tek-siparis
-- yolunu (path 1) tetikler (bundle_surface/bundle_compliance ile ayni).
INSERT INTO "ScanPackage" ("id","key","displayName","description","priceMinorUnit","modelProvider","maxToolCalls","promptTemplate","active")
VALUES (
  gen_random_uuid(), 'bundle_recon', 'Keşif Paketi',
  'Subdomain Takeover Taraması + API & Swagger Keşfi + CMS & Bilinen CVE Taraması — saldırı yüzeyinizi tek raporda haritalar (pasif keşif).',
  449900, 'cybertestify-anthropic', 30,
  'PASSIVE reconnaissance only for the Discovery bundle; final report generated by code. Target: {{TARGET_HOST}}',
  true
) ON CONFLICT ("key") DO NOTHING;
