-- bundle_active_verify icin ScanPackage satiri (Order.packageId FK). deploy seed calistirmadigi
-- icin burada olusturulur (idempotent). Rapor KOD tarafindan (generateBundleActiveVerifyReport)
-- uretilir; promptTemplate placeholder. Bu satirin varligi routes/orders.ts'te tek-siparis
-- yolunu (path 1) tetikler (bundle_surface/bundle_recon ile ayni). Fiyat bilgi amacli; siparis
-- tutari bundlePrice(...) ile hesaplanir (7 uye toplamindan %25 indirim).
INSERT INTO "ScanPackage" ("id","key","displayName","description","priceMinorUnit","modelProvider","maxToolCalls","promptTemplate","active")
VALUES (
  gen_random_uuid(), 'bundle_active_verify', 'Aktif Doğrulama Paketi',
  'Aktif-hafif zafiyet doğrulama. Enjeksiyon (SQLi/XSS) + IDOR tam işlevsel; kalan 5 kontrol aşamalı devreye alınıyor. Zafiyeti kanıtlar, istismar etmez.',
  2699475, 'cybertestify-anthropic', 30,
  'ACTIVE-LIGHT verification bundle; final report generated by code. Target: {{TARGET_HOST}}',
  true
) ON CONFLICT ("key") DO NOTHING;
