-- bundle_compliance icin ScanPackage satiri (Order.packageId FK). deploy seed calistirmadigi
-- icin burada olusturulur (idempotent). Rapor KOD tarafindan (generateBundleComplianceReport)
-- uretilir; promptTemplate placeholder.
INSERT INTO "ScanPackage" ("id","key","displayName","description","priceMinorUnit","modelProvider","maxToolCalls","promptTemplate","active")
VALUES (
  gen_random_uuid(), 'bundle_compliance', 'Uyum Paketi',
  'KVKK Ön Uyum + PCI-DSS Hazırlık + ISO 27001 Hazırlık — dışarıdan gözlemlenebilir göstergeleri ilgili ilke/maddelerle eşler (resmî uyum beyanı değildir).',
  799900, 'cybertestify-anthropic', 30,
  'PASSIVE data-collection only for the Compliance bundle; final report generated by code. Target: {{TARGET_HOST}}',
  true
) ON CONFLICT ("key") DO NOTHING;
